name: "Publish Powershell Module"

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
  
jobs:
  publish_powershell_sdk:
    name: Publish powershell SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}


      - name: Publish Module
        shell: pwsh
        run: |
          $DebugPreference="Continue"
          Install-Module -Name PSYaml -RequiredVersion 1.0.2 -Force
          Publish-Module `
              -Path './PSSailpoint' `
              -NuGetApiKey ${{ secrets.PS_GALLERY_TOKEN }} `
              -Verbose -Force
